site_name: MPU

nav: 
  - Início: index.md
  - Cronograma: cronograma.md
  - Processo de Design: processo_de_design.md
  - Perfil do usuário:
    - Questionário: questionarios.md
    - Personas: personas.md
    - Entrevistas: entrevistas.md
  - Análise de tarefas:
    - Análises: analise_tarefas.md
    # - Planejamento: planejamento_analise_tarefas.md
  - Análise de requisitos:
    - Guia de estilo: guia-de-estilo.md
    - Princípios e diretrizes: principios_gerais_diretrizes.md
  - Apresentações: 
    - 05/03/2021: presentations/05_03_2021.md
  

theme:
  name: material
  language: pt
  # font:
  #   text: Ubuntu
  #   code: Ubuntu Mono

extra_css: [_extra/extra.css]

repo_name: Interacao-Humano-Computador/2020.2-Grupo2
repo_url: https://github.com/Interacao-Humano-Computador/2020.2-Grupo2

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Interacao-Humano-Computador/2020.2-Grupo2