site_name: MPU

nav: 
  - Início: index.md
  - Cronograma: cronograma.md
  - Processo de Design: processo_de_design.md
  - Perfil do usuário:
    - Questionário: questionarios.md
    - Personas: personas.md
    - Entrevistas: entrevistas.md
  - Análise de tarefas:
    - Análises: analise_tarefas.md
  - Análise de requisitos:
    - Princípios e diretrizes: principios_gerais_diretrizes.md
    - Metas de usabilidade: metas_usabilidade.md
    - Guia de estilo: guia-de-estilo.md
  - Storyboards:
    - Planejamento dos Storyboards: storyboards/planejamento.md
    - '1. Visualização de convocados': storyboards/storyboard_1.md
    - '2. Informação sobre remuneração de cargos': storyboards/storyboard_2.md
  - Protótipos:
    - 'Protótipos de Papel: Informação sobre Remuneração': prototipo_de_papel_inf.md
    - 'Planejamento e avaliação dos protótipos de papel': plan_prot_de_papel.md
  - Apresentações: 
    - 05/03/2021: presentations/05_03_2021.md
    - 19/03/2021: presentations/19_03_2021.md
    - 26/03/2021: presentations/26_03_2021.md
    - 09/04/2021: presentations/09_04_2021.md
theme:
  name: material
  language: pt
  # font:
  #   text: Ubuntu
  #   code: Ubuntu Mono

extra_css: [_extra/extra.css]

repo_name: Interacao-Humano-Computador/2020.2-Grupo2
repo_url: https://github.com/Interacao-Humano-Computador/2020.2-Grupo2

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Interacao-Humano-Computador/2020.2-Grupo2