site_name: MPU

nav: 
  - Início: index.md
  - Cronograma: cronograma.md
  - Processo de Design: processo_de_design.md
  - Perfil do usuário:
    - Questionário: questionarios.md
    - Personas: personas.md
    - Entrevistas: entrevistas.md
  - Análise de requisitos:
    - Princípios e diretrizes: principios_gerais_diretrizes.md
    - Metas de usabilidade: metas_usabilidade.md
    - Guia de estilo: guia-de-estilo.md
  - Análise de tarefas:
    - Análises: analise_tarefas.md
    - Planejamento: planejamento-tarefas.md
  - Storyboards:
    - 1. Visualização de convocados: storyboards/storyboard_1.md
    - 2. Informação sobre remuneração de cargos: storyboards/storyboard_2.md
    - 3. Visualizar concursos: storyboards/storyboard_3.md
    - Planejamento dos Storyboards: storyboards/planejamento.md
  - Protótipos:
    - Baixa-Fidelidade:
      - Visualizar Concursos:  prototipos/prototipo_papel_concursos.md
      - Visualizar Cargos e Remuneração:  prototipos/prototipo_de_papel_inf.md
    - Alta-Fidelidade:
      - Visualizar Concursos:  prototipos/prototipo_alta_concursos.md
      - Visualizar Cargos e Remuneração:  prototipos/prototipo_de_alta_inf.md
    - Avaliação:
      - Visualizar Concursos:  prototipos/plan_prototipo_papel_concursos.md
      - Visualizar Cargos e Remuneração:  prototipos/plan_prototipo_papel_cargos.md
  - Apresentações: 
    - 05/03/2021: presentations/05_03_2021.md
    - 19/03/2021: presentations/19_03_2021.md
    - 26/03/2021: presentations/26_03_2021.md
    - 09/04/2021: presentations/09_04_2021.md
    - 23/04/2021: presentations/23_04_2021.md


theme:
  name: material
  language: pt
  # font:
  #   text: Ubuntu
  #   code: Ubuntu Mono

extra_css: [_extra/extra.css]

repo_name: Interacao-Humano-Computador/2020.2-Grupo2
repo_url: https://github.com/Interacao-Humano-Computador/2020.2-Grupo2

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Interacao-Humano-Computador/2020.2-Grupo2